[package]
name = "conway"
version = "0.0.1"
edition = "2021"
authors = ["Benny Christian Henning <benny.henning@web.de>"]
repository = "https://gitlab.com/bchenning/conway"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
termion = "1.5.6"
tui = "0.16.0"
